name: CI

on:
  push:
    branches:
      - 'main'
  pull_request: {}

defaults:
  run:
    shell: bash

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - name: Install Dependencies
        run: npm install
      - name: Prettier
        run: npm run prettier

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build

  test:
    name: Test Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22, 24]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - name: Install Dependencies
        run: npm install
      - name: Test
        run: npm run test -- --coverage
