name: Release

on:
  # Support manually pushing a new release
  workflow_dispatch: {}
  # Trigger when a release is published
  release:
    types: [published]

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Publish to NPM
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e  # v6
        with:
          node-version-file: .nvmrc
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: |
          npm install

      - name: Build project
        run: |
          npm run build

      - name: Push Release
        if: ${{ !github.event.release.prerelease }}
        run: |
          npm publish --tag latest --access=public --provenance

      - name: Push Pre-Release
        if: ${{ github.event.release.prerelease }}
        run: |
          npm publish --tag next --access=public --provenance
